trainee.file.path=classpath:trainees.csv
trainer.file.path=classpath:trainers.csv
training.file.path=classpath:trainings.csv

logging.level.com.example.gym=DEBUG
logging.level.org.springframework=INFO